"""
test_targeted_post_implementation_fix.py
=========================================
Tests for ResearchIQ Targeted Post-Implementation Fix:
  1. Full-Text Structural Validation (P001/P008 rejection, full-paper acceptance, etc.)
  2. Candidate Sentence Pool Retention & Diagnostics
  3. Patent Multi-Source Engine (EPO, Google Patents, Lens, PatentsView, Europe PMC)
"""

import os
import sys
from unittest.mock import patch, MagicMock
import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.agent_research import validate_full_paper_content, is_full_text_usable
from compression.section_parser import parse_paper_sections, inspect_and_classify_unknown_section, NON_RESEARCH_SECTIONS
from compression.textrank import segment_sentences
from compression.fact_sheet import compress_paper
from compression.token_utils import estimate_tokens
from agents.agent_patent import (
    retrieve_multi_source_patents,
    _fetch_epo_ops_patents,
    _fetch_google_patents,
    _fetch_lens_patents,
    _fetch_patentsview_patents,
    _fetch_epmc_patents,
    search_and_classify_patents,
)
from schemas import Agent2GapOutput, NovelMethodProposal


# ===========================================================================
# 1. Full-Text Structural Validation Tests (Tests 1–5)
# ===========================================================================

class TestFullTextValidation:
    def test_1_large_html_containing_only_abstract_rejected(self):
        """Large HTML payload (15k words of wrapper/ads/nav + abstract) must be rejected."""
        nav_filler = " ".join(["publisher", "journal", "volume", "citation", "metrics", "download", "cookie", "policy"] * 1500)
        html_text = f"<h1>Article Landing Page</h1><p><b>Abstract:</b> We describe synthetic audio detection in general terms.</p><div>{nav_filler}</div>"

        is_valid, reason, stats = validate_full_paper_content(html_text)
        assert is_valid is False
        assert "only abstract/non-research" in reason or "publisher wrapper" in reason

    def test_2_full_research_paper_accepted(self):
        """Genuine research paper with Introduction, Methodology, and Results is accepted."""
        paper_text = """
1. Introduction
Deepfake audio detection is an important challenge in security and digital forensics.
Recent advancements in neural vocoders make synthetic speech difficult to distinguish from genuine human speech.
In this paper, we propose a multi-feature fusion network to capture temporal and spectral artifacts.

2. Methodology
Our proposed architecture extracts MFCC and constant-Q transform features from 16kHz audio clips.
The features are processed by a dual-branch convolutional neural network with bidirectional LSTM layers.
We employ cross-entropy loss combined with center loss to maximize inter-class feature separation.

3. Experimental Results
We evaluated the framework on the ASVspoof 2019 and 2021 evaluation benchmarks.
Our model achieved an equal error rate of 1.42% and minimum tandem detection cost function of 0.052.
The proposed method outperforms standard baseline models across all acoustic conditions.

4. Conclusion
We presented a novel acoustic verification framework for synthetic speech detection.
Future work will investigate cross-codec generalization and low-resource adaptation.
"""
        is_valid, reason, stats = validate_full_paper_content(paper_text)
        assert is_valid is True
        assert reason == "valid_research_paper"
        assert len(stats["research_sections"]) >= 3

    def test_3_abstract_and_funding_only_rejected(self):
        """Paper content containing only abstract and funding notes must be rejected."""
        text = """
Abstract
This paper provides an overview of modern machine learning techniques for signal processing.
We survey recent deep learning architectures and summarize ongoing open questions in the domain.

Funding Information
This research was funded by the National Science Foundation under Grant No. IIS-1900123.
"""
        is_valid, reason, stats = validate_full_paper_content(text)
        assert is_valid is False
        assert "only abstract/non-research" in reason

    def test_4_full_paper_with_unusual_section_names_accepted(self):
        """Full paper with domain-specific section names (e.g. Acoustic Formulation, Case Study) is accepted."""
        text = """
1. Background and Overview
Acoustic feature representation plays a pivotal role in detecting manipulated voices.
We study spectral envelopes and phase inconsistencies generated by generative models.

2. Acoustic Formulation and Architecture
Let x(t) denote the raw audio waveform sampled at 16 kHz.
We compute the short-time Fourier transform with a Hanning window of size 512.
The spectral coefficients are fed to a convolutional residual block with residual skip connections.

3. Case Study and Quantitative Results
On the benchmark corpus, our architecture attains 96.8% accuracy and 0.985 AUROC.
Ablation analysis reveals that high-frequency phase features contribute 4.2% absolute gain.

4. Concluding Remarks
Phase features significantly enhance robustness against acoustic perturbations.
"""
        is_valid, reason, stats = validate_full_paper_content(text)
        assert is_valid is True
        assert reason == "valid_research_paper"

    def test_5_unknown_section_containing_research_preserved(self):
        """Unknown section with substantive research prose and vocabulary is preserved and accepted."""
        unknown_text = """
We investigate the impact of audio compression codecs on synthetic voice detection.
Our experimental pipeline processes 10,000 speech samples encoded with MP3, AAC, and Opus codecs at various bitrates.
The deep convolutional neural network extracts 128-dimensional latent embeddings to perform binary classification.
Experimental evaluation demonstrates that our model maintains 94.5% detection accuracy under 32 kbps compression.
Furthermore, we observe that high-pass filtering removes high-frequency synthetic artifacts produced by neural vocoders.
We analyze the feature distributions using t-SNE visualizations and find well-separated clusters for bona fide speech.
"""
        is_valid, reason, stats = validate_full_paper_content(unknown_text)
        assert is_valid is True
        assert reason == "valid_research_paper"


# ===========================================================================
# 2. Candidate Sentence Pool Retention & Diagnostics Tests (Tests 6–10)
# ===========================================================================

class TestCandidateSentencePool:
    def test_6_research_tokens_not_unnecessarily_removed(self):
        """Valid research sentences are retained in the candidate pool."""
        text = """
Introduction
Deep learning has revolutionized computer vision and natural language processing.
In this work, we study gradient descent dynamics in deep networks.

Methodology
We formulate the loss function as empirical risk minimization with L2 weight decay.
The parameter updates follow stochastic gradient descent with momentum 0.9.

Results
The proposed algorithm converges in 45 epochs, achieving 98.2% test accuracy.
"""
        paper_dict = {
            "title": "Optimization Dynamics in Deep Learning",
            "full_text": text,
            "coverage_type": "full_paper"
        }
        fact_sheet = compress_paper(paper_dict, paper_id="P-TEST")
        # Fact sheet should retain substantial sentences
        assert len(fact_sheet.all_sentences()) >= 4

    def test_7_technical_sentences_remain_candidates(self):
        """Sentences with technical terminology and hyperparameter settings remain candidates."""
        s = "We set batch size = 64, learning rate = 1e-4, and Adam optimizer with beta1 = 0.9."
        sentences = segment_sentences(s)
        assert len(sentences) == 1
        assert "batch size = 64" in sentences[0]

    def test_8_numerical_and_statistical_sentences_remain_candidates(self):
        """Sentences with p-values, statistics, and percentages are retained by segment_sentences."""
        text = "Our method improved accuracy by 14.5% (p < 0.001, 95% CI [12.1, 16.9]). We report mean ± SD of 88.4 ± 2.1."
        sentences = segment_sentences(text)
        assert len(sentences) == 2
        assert "p < 0.001" in sentences[0]
        assert "88.4 ± 2.1" in sentences[1]

    def test_9_references_are_excluded_from_candidate_pool(self):
        """Pure reference lists are correctly excluded from research candidates."""
        ref_text = """
[1] A. Smith and B. Jones, "Deep speech synthesis," IEEE Trans. Audio, vol. 12, pp. 45-56, 2020.
[2] C. Wang et al., "Voice anti-spoofing," in Proc. Interspeech, 2021, pp. 112-116.
[3] D. Lee, "Neural vocoders," doi:10.1109/TASLP.2022.1234567, 2022.
[4] E. Brown, "Acoustic detection," arXiv:2104.01234, 2021.
"""
        classified = inspect_and_classify_unknown_section(ref_text, "References")
        assert classified == "references"

    def test_10_candidate_pool_diagnostics_correct(self, capsys):
        """Compressing a paper outputs the required candidate pool diagnostics."""
        paper_text = """
Introduction
Speech synthesis has progressed rapidly with neural network models.
Detecting manipulated speech requires understanding acoustic spectral properties.

Methodology
We extract spectrograms and compute log mel filterbank energies.
The classification backbone uses a residual convolutional network.

Results
On the test set, we obtain an EER of 2.1%.
Baseline models achieved an EER of 5.8%.

References
[1] Author A, "Title A," Journal A, 2021.
[2] Author B, "Title B," Journal B, 2022.
"""
        paper_dict = {
            "title": "Speech Synthesis Detection",
            "full_text": paper_text,
            "coverage_type": "full_paper"
        }
        compress_paper(paper_dict, paper_id="P-DIAG")
        captured = capsys.readouterr().out
        assert "P-DIAG Diagnostics:" in captured
        assert "Original raw tokens" in captured
        assert "Research text tokens" in captured
        assert "Excluded non-research tokens" in captured
        assert "Sentence extraction tokens" in captured
        assert "Candidate pool tokens" in captured


# ===========================================================================
# 3. Patent Multi-Source Engine Tests (Tests 11–18)
# ===========================================================================

class TestPatentMultiSourceEngine:
    def test_11_epo_success(self):
        """EPO OPS returns patents when credentials and API respond successfully."""
        with patch.dict(os.environ, {"EPO_OPS_CONSUMER_KEY": "test_key", "EPO_OPS_CONSUMER_SECRET": "test_secret"}):
            with patch("agents.agent_patent.urllib.request.urlopen") as mock_urlopen:
                # Mock token response + search response
                token_resp = MagicMock()
                token_resp.read.return_value = b'{"access_token": "mock_token"}'
                search_resp = MagicMock()
                search_resp.read.return_value = b'{"ops:world-patent-data": {"ops:biblio-search": {"ops:search-result": {"ops:publication-reference": [{"document-id": {"country": {"$": "EP"}, "doc-number": {"$": "3456789"}, "kind": {"$": "A1"}}}]}}}}'

                mock_urlopen.side_effect = [MagicMock(__enter__=MagicMock(return_value=token_resp)), MagicMock(__enter__=MagicMock(return_value=search_resp))]

                patents, status = _fetch_epo_ops_patents(["deepfake audio"])
                assert status == "SUCCESS"
                assert len(patents) >= 1
                assert patents[0]["patent_id"] == "EP3456789A1"

    def test_12_epo_missing_credentials(self):
        """EPO returns SKIPPED_NO_CREDENTIALS when credentials are not in environment."""
        with patch.dict(os.environ, {"EPO_OPS_CONSUMER_KEY": "", "EPO_OPS_CONSUMER_SECRET": ""}, clear=True):
            patents, status = _fetch_epo_ops_patents(["deepfake audio"])
            assert patents == []
            assert status == "SKIPPED_NO_CREDENTIALS"

    def test_13_lens_missing_credentials(self):
        """Lens returns SKIPPED_NO_CREDENTIALS when LENS_API_TOKEN is not in environment."""
        with patch.dict(os.environ, {"LENS_API_TOKEN": ""}, clear=True):
            patents, status = _fetch_lens_patents(["deepfake audio"])
            assert patents == []
            assert status == "SKIPPED_NO_CREDENTIALS"

    def test_14_google_unavailable_on_503(self):
        """Google Patents marks SOURCE_UNAVAILABLE when server returns 503."""
        import urllib.error
        with patch("agents.agent_patent.urllib.request.urlopen", side_effect=urllib.error.HTTPError("url", 503, "Service Unavailable", {}, None)):
            patents, status = _fetch_google_patents(["deepfake audio"])
            assert patents == []
            assert status == "SOURCE_UNAVAILABLE"

    def test_15_partial_multi_source_success(self):
        """When at least one source succeeds and others are skipped/unavailable, overall is PARTIAL_SUCCESS."""
        mock_patent = {
            "patent_id": "EP1122334A1",
            "publication_number": "EP1122334A1",
            "title": "Voice spoofing detection system",
            "assignee": "Cyber Corp",
            "abstract": "Acoustic spoofing detection using spectrograms.",
            "source": "EPO",
            "sources": ["EPO"],
            "jurisdiction": "EP"
        }
        with patch("agents.agent_patent._fetch_epo_ops_patents", return_value=([mock_patent], "SUCCESS")), \
             patch("agents.agent_patent._fetch_google_patents", return_value=([], "SOURCE_UNAVAILABLE")), \
             patch("agents.agent_patent._fetch_lens_patents", return_value=([], "SKIPPED_NO_CREDENTIALS")), \
             patch("agents.agent_patent._fetch_patentsview_patents", return_value=([], "SOURCE_UNAVAILABLE")), \
             patch("agents.agent_patent._fetch_epmc_patents", return_value=([], "NO_RESULTS")):

            patents, source_statuses, overall_status = retrieve_multi_source_patents("Deepfake audio detection")
            assert len(patents) == 1
            assert overall_status == "PARTIAL_SUCCESS"
            assert source_statuses["EPO"] == "SUCCESS"
            assert source_statuses["Lens"] == "SKIPPED_NO_CREDENTIALS"

    def test_16_all_source_failure(self):
        """When all sources fail or are skipped with 0 patents, status is RETRIEVAL_FAILED."""
        with patch("agents.agent_patent._fetch_epo_ops_patents", return_value=([], "SKIPPED_NO_CREDENTIALS")), \
             patch("agents.agent_patent._fetch_google_patents", return_value=([], "SOURCE_UNAVAILABLE")), \
             patch("agents.agent_patent._fetch_lens_patents", return_value=([], "SKIPPED_NO_CREDENTIALS")), \
             patch("agents.agent_patent._fetch_patentsview_patents", return_value=([], "SOURCE_UNAVAILABLE")), \
             patch("agents.agent_patent._fetch_epmc_patents", return_value=([], "NO_RESULTS")):

            patents, source_statuses, overall_status = retrieve_multi_source_patents("Deepfake audio detection")
            assert patents == []
            assert overall_status == "RETRIEVAL_FAILED"

    def test_17_zero_result_distinction(self):
        """Distinguishes NO_RESULTS (clean zero hits) from API failure/credentials skipping."""
        with patch("agents.agent_patent._fetch_epo_ops_patents", return_value=([], "NO_RESULTS")), \
             patch("agents.agent_patent._fetch_google_patents", return_value=([], "NO_RESULTS")), \
             patch("agents.agent_patent._fetch_lens_patents", return_value=([], "NO_RESULTS")), \
             patch("agents.agent_patent._fetch_patentsview_patents", return_value=([], "NO_RESULTS")), \
             patch("agents.agent_patent._fetch_epmc_patents", return_value=([], "NO_RESULTS")):

            patents, source_statuses, overall_status = retrieve_multi_source_patents("Rare Topic")
            assert patents == []
            assert overall_status == "NO_RESULTS"

    def test_18_real_patent_preservation_on_gemini_fallback(self):
        """Retrieved real patents are never replaced with fake data when Gemini is unavailable."""
        gap_data = Agent2GapOutput(
            gaps=[],
            proposed_method=NovelMethodProposal(
                title="Spectral Inversion Detector",
                approach="Spectrogram analysis",
                novelty_score=85,
                rationale="Novel approach"
            )
        )
        real_patent = {
            "patent_id": "US11223344B2",
            "publication_number": "US11223344B2",
            "title": "Real Audio Deepfake Detection System",
            "assignee": "Acoustic Intelligence Inc.",
            "applicant": "Acoustic Intelligence Inc.",
            "inventors": ["Dr. Alice"],
            "abstract": "A neural network system for acoustic verification.",
            "claims": "1. A method for audio verification.",
            "source": "Google Patents",
            "sources": ["Google Patents"],
            "jurisdiction": "US",
            "relevance_score": 88
        }
        with patch("agents.agent_patent.retrieve_multi_source_patents", return_value=([real_patent], {"Google Patents": "SUCCESS"}, "SUCCESS")), \
             patch("agents.agent_patent._classify_patents_with_gemini", side_effect=RuntimeError("RESOURCE_EXHAUSTED")):

            result = search_and_classify_patents(gap_data, "Deepfake audio detection")
            assert result.patent_retrieval_status == "SUCCESS"
            assert result.patent_analysis_status == "retrieval_success_synthesis_failed"
            assert len(result.patents) == 1
            assert result.patents[0].patent_id == "US11223344B2"
            assert result.patents[0].assignee == "Acoustic Intelligence Inc."
            assert result.patents[0].relevance_score == 88
