import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import json
import google.generativeai as genai
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from dotenv import load_dotenv

from schemas import ProjectReportState  # type: ignore

# Load environment variables
load_dotenv()

# Configure Gemini
api_key = os.getenv("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)

def compile_final_report(state: ProjectReportState, output_dir: str = ".") -> str:
    """
    Synthesizes executive summary and generates the final PDF report.
    Returns the absolute path to the generated PDF file.
    """
    summary_narrative = (
        "This report reviews active literature and patents in distributed system architectures. "
        "Key opportunities lie in benchmark standardization across multi-institutional datasets."
    )
    
    prompt = f"""
    You are a Lead Research Director compiling a final executive summary.
    Review the following structured inputs:
    
    Research Papers:
    {json.dumps([p.model_dump() for p in state.research.papers], indent=2)}
    
    Identified Gaps:
    {json.dumps([g.model_dump() for g in state.gaps.gaps], indent=2)}
    
    Active Patents:
    {json.dumps([pat.model_dump() for pat in state.patents.patents], indent=2)}
    
    Write a 2-paragraph cohesive Executive Summary that:
    1. Highlights the main trend in the research papers.
    2. Explains how the proposed method resolves the critical gaps without infringing on the active patents.
    
    Respond ONLY with the text of the Executive Summary.
    """
    
    try:
        model = genai.GenerativeModel('gemini-1.5-flash')
        response = model.generate_content(prompt)
        summary_narrative = response.text.strip()
    except Exception as e:
        print(f"Error calling Gemini in Agent 4 compiler: {e}")
        
    filename = f"report_{state.topic.lower().replace(' ', '_')}.pdf"
    file_path = os.path.join(output_dir, filename)
    
    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=54, leftMargin=54, topMargin=54, bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Styles for premium aesthetics
    title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=26,
        leading=32,
        textColor=colors.HexColor('#1A365D'),
        spaceAfter=15
    )
    
    meta_style = ParagraphStyle(
        'CoverMeta',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        leading=15,
        textColor=colors.HexColor('#4A5568'),
        spaceAfter=8
    )
    
    h1_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#2B6CB0'),
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    h2_style = ParagraphStyle(
        'SubHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#2D3748'),
        spaceBefore=8,
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#2D3748'),
        spaceAfter=8
    )

    story = []
    
    # --- PAGE 1: COVER PAGE ---
    story.append(Spacer(1, 100))
    story.append(Paragraph("RESEARCH INTELLIGENCE & PATENT BRIEF", title_style))
    story.append(Spacer(1, 10))
    story.append(Paragraph(f"Topic Focus: {state.topic}", ParagraphStyle('Focus', parent=title_style, fontSize=16, textColor=colors.HexColor('#2B6CB0'))))
    story.append(Spacer(1, 150))
    story.append(Paragraph("<b>Generated By:</b> ResearchIQ Multi-Agent Engine", meta_style))
    story.append(Paragraph("<b>Date:</b> June 30, 2025", meta_style))
    story.append(Spacer(1, 40))
    
    disclaimer_text = (
        "<i>Disclaimer: This report represents an AI-generated synthesis of public academic articles and patent databases. "
        "It is designed solely to assist research orientation and understanding. All source materials must be consulted directly "
        "before citing or implementing findings.</i>"
    )
    story.append(Paragraph(disclaimer_text, ParagraphStyle('Disclaimer', parent=body_style, fontSize=8, leading=11, textColor=colors.HexColor('#718096'))))
    story.append(PageBreak())
    
    # --- PAGE 2: EXECUTIVE SUMMARY ---
    story.append(Paragraph("Executive Summary", h1_style))
    story.append(Paragraph(summary_narrative, body_style))
    story.append(Spacer(1, 15))
    
    # --- PAGE 2: RESEARCH PAPERS LANDSCAPE ---
    story.append(Paragraph("Academic Research Landscape", h1_style))
    story.append(Paragraph("The following papers represent the top-ranked relevant publications from multi-platform API searches:", body_style))
    
    # Table of papers
    table_data = [["Title", "Rank", "Notebook Summary"]]
    for paper in state.research.papers[:5]:
        short_title = paper.title[:50] + "..." if len(paper.title) > 50 else paper.title
        short_summary = paper.notebook_summary[:80] + "..." if len(paper.notebook_summary) > 80 else paper.notebook_summary
        table_data.append([
            Paragraph(f"<b>{short_title}</b><br/><font size=7 color='#718096'>By {', '.join(paper.authors[:2])} ({paper.year})</font>", body_style),
            Paragraph(f"<font color='#2B6CB0'><b>{paper.relevance_rank}</b></font>", body_style),
            Paragraph(short_summary, body_style)
        ])
        
    t = Table(table_data, colWidths=[180, 60, 264])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#E2E8F0')),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E0')),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    story.append(t)
    story.append(PageBreak())
    
    # --- PAGE 3: GAPS & METHOD PROPOSAL ---
    story.append(Paragraph("Research Gap Analysis", h1_style))
    story.append(Paragraph("Key weaknesses identified in current published literature:", body_style))
    
    for idx, gap in enumerate(state.gaps.gaps, 1):
        severity_color = "#E53E3E" if gap.severity == "Critical" else "#DD6B20"
        gap_html = f"""
        <b>Gap #{idx} [<font color="{severity_color}">{gap.severity}</font>]</b>: {gap.description}<br/>
        <b>Why it matters:</b> {gap.why_it_matters}<br/>
        <i>Sources: {', '.join(gap.evidence_papers[:2])}</i>
        """
        
        # Render each gap as a styled visual callout card using a 1x1 table
        gap_table = Table([[Paragraph(gap_html, body_style)]], colWidths=[504])
        gap_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F7FAFC')),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
            ('LINELEFT', (0,0), (-1,-1), 4, colors.HexColor(severity_color)),
            ('TOPPADDING', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 10),
            ('LEFTPADDING', (0,0), (-1,-1), 15),
            ('RIGHTPADDING', (0,0), (-1,-1), 15),
        ]))
        story.append(gap_table)
        story.append(Spacer(1, 10))
        
    story.append(Spacer(1, 10))
    story.append(Paragraph("Proposed Combined Methodology", h1_style))
    story.append(Paragraph(f"<b>Proposed Title:</b> {state.gaps.proposed_method.title}", h2_style))
    
    # Render methodology as a structured system architecture block diagram
    steps_html = f"<b>Execution Architecture Steps:</b><br/>"
    for step_idx, step in enumerate(state.gaps.proposed_method.approach.split("\n"), 1):
        if step.strip():
            steps_html += f"<b>Step {step_idx}:</b> {step.strip()}<br/>"
            
    method_table = Table([[Paragraph(steps_html, body_style)]], colWidths=[504])
    method_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#EBF8FF')),
        ('BOX', (0,0), (-1,-1), 1.5, colors.HexColor('#60A5FA')),
        ('TOPPADDING', (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
        ('LEFTPADDING', (0,0), (-1,-1), 15),
        ('RIGHTPADDING', (0,0), (-1,-1), 15),
    ]))
    story.append(method_table)
    story.append(PageBreak())
    
    # --- PAGE 4: PATENT LANDSCAPE & RECOMMENDATIONS ---
    story.append(Paragraph("Intellectual Property Landscape", h1_style))
    story.append(Paragraph("Evaluation of active patents and FTO (Freedom to Operate) checks:", body_style))
    
    # Patent Table with FTO Rating & Actionable Design-Around Strategy
    patent_headers = [["Patent ID", "Assignee", "FTO Rating", "Design-Around Strategy"]]
    pt_data = patent_headers
    
    # Row color styling rules
    row_styles = []
    
    for row_idx, pat in enumerate(state.patents.patents, 1):
        fto_color = "#E53E3E" if pat.fto_rating == "Alert" else ("#DD6B20" if pat.fto_rating == "Caution" else "#38A169")
        pt_data.append([
            Paragraph(f"<b>{pat.patent_id}</b><br/><font size=7 color='#718096'>{pat.title[:30]}...</font>", body_style),
            Paragraph(pat.assignee, body_style),
            Paragraph(f"<b><font color='{fto_color}'>{pat.fto_rating}</font></b>", body_style),
            Paragraph(pat.design_around_strategy, body_style)
        ])
        
    pt = Table(pt_data, colWidths=[80, 90, 70, 264])
    pt.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#E2E8F0')),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E0')),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    story.append(pt)
    
    story.append(Spacer(1, 15))
    story.append(Paragraph("Unpatented White Space Opportunities", h2_style))
    for opp in state.patents.white_space_opportunities:
        story.append(Paragraph(f"• <b>{opp}</b>", body_style))
        
    # Build Document
    doc.build(story)
    
    return os.path.abspath(file_path)
