import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import json
import google.generativeai as genai
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from dotenv import load_dotenv

from schemas import ProjectReportState  # type: ignore

# Load environment variables
load_dotenv()

# Configure Gemini
api_key = os.getenv("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)

def compile_final_report(state: ProjectReportState, output_dir: str = ".") -> str:
    """
    Synthesizes executive summary and generates the final PDF report.
    Returns the absolute path to the generated PDF file.
    """
    # 1. Synthesize plain-text Executive Summary and Collaborators using Gemini
    summary_narrative = (
        "This report reviews active literature and patents in distributed system architectures. "
        "Key opportunities lie in benchmark standardization across multi-institutional datasets."
    )
    
    prompt = f"""
    You are a Lead Research Director compiling a final executive summary.
    Review the following structured inputs:
    
    Research Papers:
    {json.dumps([p.model_dump() for p in state.research.papers], indent=2)}
    
    Identified Gaps:
    {json.dumps([g.model_dump() for g in state.gaps.gaps], indent=2)}
    
    Active Patents:
    {json.dumps([pat.model_dump() for pat in state.patents.patents], indent=2)}
    
    Write a 2-paragraph cohesive Executive Summary that:
    1. Highlights the main trend in the research papers.
    2. Explains how the proposed method resolves the critical gaps without infringing on the active patents.
    
    Respond ONLY with the text of the Executive Summary.
    """
    
    try:
        model = genai.GenerativeModel('gemini-1.5-flash')
        response = model.generate_content(prompt)
        summary_narrative = response.text.strip()
    except Exception as e:
        print(f"Error calling Gemini in Agent 4 compiler: {e}")
        
    # 2. Build the PDF Document
    filename = f"report_{state.topic.lower().replace(' ', '_')}.pdf"
    file_path = os.path.join(output_dir, filename)
    
    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=54, leftMargin=54, topMargin=54, bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Styles for premium aesthetics
    title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=28,
        leading=34,
        textColor=colors.HexColor('#1A365D'),
        spaceAfter=15
    )
    
    meta_style = ParagraphStyle(
        'CoverMeta',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#4A5568'),
        spaceAfter=10
    )
    
    h1_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#2B6CB0'),
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    h2_style = ParagraphStyle(
        'SubHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#2D3748'),
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#2D3748'),
        spaceAfter=10
    )

    story = []
    
    # --- PAGE 1: COVER PAGE ---
    story.append(Spacer(1, 100))
    story.append(Paragraph("RESEARCH INTELLIGENCE & PATENT BRIEF", title_style))
    story.append(Spacer(1, 10))
    story.append(Paragraph(f"Topic Focus: {state.topic}", ParagraphStyle('Focus', parent=title_style, fontSize=18, textColor=colors.HexColor('#2B6CB0'))))
    story.append(Spacer(1, 150))
    story.append(Paragraph("<b>Generated By:</b> ResearchIQ Multi-Agent Engine", meta_style))
    story.append(Paragraph("<b>Date:</b> June 30, 2025", meta_style))
    story.append(Spacer(1, 40))
    
    # Plagiarism Disclaimer
    disclaimer_text = (
        "<i>Disclaimer: This report represents an AI-generated synthesis of public academic articles and patent databases. "
        "It is designed solely to assist research orientation and understanding. All source materials must be consulted directly "
        "before citing or implementing findings.</i>"
    )
    story.append(Paragraph(disclaimer_text, ParagraphStyle('Disclaimer', parent=body_style, fontSize=8, leading=11, textColor=colors.HexColor('#718096'))))
    story.append(PageBreak())
    
    # --- PAGE 2: EXECUTIVE SUMMARY ---
    story.append(Paragraph("Executive Summary", h1_style))
    story.append(Paragraph(summary_narrative, body_style))
    story.append(Spacer(1, 15))
    
    # --- SECTION: RESEARCH PAPERS LANDSCAPE ---
    story.append(Paragraph("Academic Research Landscape", h1_style))
    story.append(Paragraph("The following papers represent the top-ranked relevant publications for this query:", body_style))
    
    table_data = [["Title", "Authors", "Year", "Relevance"]]
    for paper in state.research.papers[:5]: # Top 5 papers
        short_title = paper.title[:50] + "..." if len(paper.title) > 50 else paper.title
        short_authors = paper.authors[0] + " et al." if len(paper.authors) > 1 else (paper.authors[0] if paper.authors else "Unknown")
        table_data.append([short_title, short_authors, str(paper.year), f"{int(paper.relevance_score * 100)}%"])
        
    t = Table(table_data, colWidths=[200, 150, 50, 60])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#E2E8F0')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#2D3748')),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E0')),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t)
    story.append(PageBreak())
    
    # --- PAGE 3: GAPS & METHOD PROPOSAL ---
    story.append(Paragraph("Research Gap Analysis", h1_style))
    for idx, gap in enumerate(state.gaps.gaps, 1):
        story.append(Paragraph(f"<b>Gap #{idx} [{gap.severity}]:</b> {gap.description}", body_style))
        story.append(Paragraph(f"<i>Source Proof:</i> {', '.join(gap.evidence_papers)}", ParagraphStyle('Evidence', parent=body_style, leftIndent=20, fontName='Helvetica-Oblique')))
        story.append(Spacer(1, 5))
        
    story.append(Spacer(1, 15))
    story.append(Paragraph("Proposed Combined Methodology", h1_style))
    story.append(Paragraph(f"<b>Proposed Title:</b> {state.gaps.proposed_method.title}", h2_style))
    story.append(Paragraph(f"<b>Steps:</b><br/>{state.gaps.proposed_method.approach.replace(chr(10), '<br/>')}", body_style))
    story.append(Paragraph(f"<b>Novelty Rationale:</b> {state.gaps.proposed_method.rationale}", body_style))
    story.append(PageBreak())
    
    # --- PAGE 4: PATENT LANDSCAPE ---
    story.append(Paragraph("Intellectual Property Landscape", h1_style))
    story.append(Paragraph("Comparison of the proposed method against active patents:", body_style))
    
    patent_table = [["Patent ID", "Assignee", "Classification", "Relevance Summary"]]
    for pat in state.patents.patents:
        patent_table.append([pat.patent_id, pat.assignee, pat.relevance, pat.summary])
        
    pt = Table(patent_table, colWidths=[80, 100, 80, 200])
    pt.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#E2E8F0')),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E0')),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(pt)
    
    story.append(Spacer(1, 15))
    story.append(Paragraph("Open IP White Spaces", h2_style))
    for opp in state.patents.white_space_opportunities:
        story.append(Paragraph(f"• {opp}", body_style))
        
    # Build Document
    doc.build(story)
    
    return os.path.abspath(file_path)
